import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryClientProviders from "@/providers/query-client-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Query client is provided via a client-only provider to avoid Server/Client boundary issues

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProviders>{children}</QueryClientProviders>
      </body>
    </html>
  );
}
